added posibility to delete instituions (its not added at back so its …
TV3ntu/PDS-2024-frontend pull request #129
Opened 2024-06-14 22:19 UTC by ivoFerDev

…unusable right now)

2024-06-18 15:09 UTC, agusnarvaez requested changes
Avisame cuando revises eso que quedó para cambiarl, el resto está ok

2024-06-18 15:09 UTC, agusnarvaez commented on src/app/pages/admin-page/admin-page.component.ts
> +  institutions: InstitutionResponse[]=[]
Esto debería ser de tipo Institution

2024-06-18 15:09 UTC, agusnarvaez commented on src/app/services/institution/institution.service.ts
> +export interface InstitutionResponse{
No sería necesario si en admin-page.component usás la clase Institution

2024-06-18 18:59 UTC, ivoFerDev commented on src/app/services/institution/institution.service.ts
> +export interface InstitutionResponse{
ademas Tuve que modificar la clase entity, curse, institucion para que funque xq sino tiraba error xq no tenia name el modelo de institucion

2024-06-18 19:00 UTC, ivoFerDev commented
Ahi corregi lo que quedaba

2024-06-18 19:19 UTC, agusnarvaez requested changes

2024-06-18 19:19 UTC, agusnarvaez commented on src/app/models/entity.ts
> +    name:string
Esto no debería estar

2024-06-18 19:19 UTC, agusnarvaez commented on src/app/pages/admin-page/admin-page.component.ts
> +      this.institutions = institutions})
Fijate como lo maneja el entity-list:

```typescript
 getInstitutions(){
    this.institutionService.getAll(this.filter)
    .subscribe(institutions => {
      const transformedInstitutions = institutions.map(institution => {
        return {
            ...institution,  // Copia todas las propiedades existentes
            title: institution.name,
        }
      })
      this.entityList = transformedInstitutions;
    })
  }
```

2024-06-19 03:51 UTC, agusnarvaez approved these changes

2024-06-19 03:51 UTC, merged