crea la institution card
TV3ntu/PDS-2024-frontend pull request #57
Opened 2024-04-17 22:57 UTC by ivoFerDev

![imagen](https://github.com/TV3ntu/PDS-2024-frontend/assets/63321183/8ebc44fc-f85b-4530-bb40-402c1d5be5b3)

2024-04-17 23:10 UTC, agusnarvaez requested changes

2024-04-17 23:10 UTC, agusnarvaez commented on src/app/pages/institution/institution.component.html
> +        <h1>Title</h1>
Estos valores pasáselos por parámetro, por ejemplo:

`{{title}}`

2024-04-17 23:10 UTC, agusnarvaez commented on src/app/pages/institution/institution.component.spec.ts
> +
Agregar elementos para parametrizar:
```
name: string
category: string
image: string
description: string
```

2024-04-17 23:10 UTC, agusnarvaez commented on src/app/pages/institution/institution.component.html
> +        <h1>Title</h1>
También ojo con los tag `h`, solo puede haber un `h1` por página, y calculo que lo vamos a tener en el hader, así que usate un h2.
Lo mismo con la línea 9, debería ser un h3. Lo podés usar para `{{category}}`

2024-04-17 23:10 UTC, agusnarvaez commented on src/app/pages/institution/institution.component.html
> +        <div>The Shiba Inu is the smallest of the six original and distinct spitz breeds of dog
Revisá que esté parametrizado, y que sea una etiqueta `<p>`

2024-04-19 18:44 UTC, ivoFerDev commented
Ahi subi en otro commit las modificaciones hechas.

2024-04-20 12:52 UTC, agusnarvaez approved these changes

2024-04-20 12:53 UTC, agusnarvaez commented
Listo para mergear!

2024-04-21 01:27 UTC, merged